spring:
  datasource:
    url: jdbc:mysql://sql.freedb.tech:3306/freedb_DUSBA0ny?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: u_6utzcz
    password: LMjJgBrGqQMV
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: SkillBridgeDevPool
      minimum-idle: 2
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true